import Head from "next/head";
import About from "../components/About";
import Banner from "../components/Banner";
import Nav from "../components/Nav";
import Testimonials from "../components/Testimonials";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <Banner />
      <About />
      <Testimonials />
    </div>
  );
}
